[connection]
baudrate = 115200
bytesize = 8
parity = "N"
stopbits = 1


[[Sensor]]
register = 2101
name = "HP inlet temperature"
component = "Sensor"
device_class = "temperature"
state_class = "measurement"
unit_of_measure = "°C"
scale = 0.1

[[Sensor]]
register = 2102
name = "DHW temperature"
component = "Sensor"
device_class = "temperature"
state_class = "measurement"
unit_of_measure = "°C"
scale = 0.1

[[Sensor]]
register = 2103
name = "Outside temperature"
component = "Sensor"
device_class = "temperature"
state_class = "measurement"
unit_of_measure = "°C"
scale = 0.1

[[Sensor]]
register = 2104
name = "HP outlet temperature"
component = "Sensor"
device_class = "temperature"
state_class = "measurement"
unit_of_measure = "°C"
scale = 0.1


[[Sensor]]
register = 2105
name = "Evaporating temperature"
component = "Sensor"
device_class = "temperature"
state_class = "measurement"
unit_of_measure = "°C"
scale = 0.1

[[Sensor]]
register = 2106
name = "Compressor temperature"
component = "Sensor"
device_class = "temperature"
state_class = "measurement"
unit_of_measure = "°C"
scale = 0.1

[[Sensor]]
register = 2107
name = "Alternative source temperature"
component = "Sensor"
device_class = "temperature"
state_class = "measurement"
unit_of_measure = "°C"
scale = 0.1

[[Sensor]]
register = 2109
name = "Pool temperature"
component = "Sensor"
device_class = "temperature"
state_class = "measurement"
unit_of_measure = "°C"
scale = 0.1

[[Sensor]]
register = 2130
name = "Loop 1 temperature"
component = "Sensor"
device_class = "temperature"
state_class = "measurement"
unit_of_measure = "°C"
scale = 0.1

[[Sensor]]
register = 2110
name = "Loop 2 temperature"
component = "Sensor"
device_class = "temperature"
state_class = "measurement"
unit_of_measure = "°C"
scale = 0.1


[[Sensor]]
register = 2160
name = "Loop 1 thermostat temperature"
component = "Sensor"
device_class = "temperature"
state_class = "measurement"
unit_of_measure = "°C"
scale = 0.1

[[Sensor]]
register = 2161
name = "Loop 2 thermostat temperature"
component = "Sensor"
device_class = "temperature"
state_class = "measurement"
unit_of_measure = "°C"
scale = 0.1
